### PR TITLE
fix: Update EMR configuration and add run-if file to deploy any region

### PR DESCRIPTION
**Pull request by kwpark-amzn**
Issue #, if available:

Description of changes: 
- Current SWB can be just deployed us-east-1 region because of hard coding in addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/emr-cluster.cfn.yml.
- To  deploy any region  EMR cfn configuration update and run-if file to add into main/solution/post-deployment/config/environment-files/ is needed.

Checklist: 

* [x] Have you successfully deployed to an AWS account with your changes? 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jn1119 — COMMENTED** [review]
1. Can you update your commit message and prefix it with 'fix: '
2. What is the error when you tried deploying in another region besides `us-east-1`. Why does downloading the file cross region not work?

**Comment by kwpark-amzn** [comment]
This is related with #123. 

Fail to bootstrap "us-east-1.elasticmapreduce/bootstrap-actions/run-if" on non us-east-1 region.
EMRFS could not download bootstrap file on other region. Thus it makes below problem.
"Master instance failed attempting to download bootstrap action 1 file from S3."

If you try to deploy SWB on Seoul region, you could know what it is exaclty.

**Review by jn1119 — COMMENTED** [review]
Can we download the local `run-if` file only if the original file fails to download? Or can we use the local file only in regions where we see the error. My concern is that this `run-if` file is copied from EMR's repository and it can go through change and it would be hard to maintain that. We need to root cause this better that why the file cannot be downloaded cross-region.

**Comment by kwpark-amzn** [comment]
I did not succeed to adop 1 you recommended even though I tried to edit cfn template in various ways. 
Could you let me know how I can adopt it?

**Review by SanketD92 — CHANGES_REQUESTED** [review]
Could you update this PR to be against the develop branch? 

According to our updated processes, once your changes are merged to the develop branch and all tests pass on our workflow environment, they will be automatically merged into mainline.

**Review by jn1119 — COMMENTED** [review]
I was able to verify that EMR provisioning worked and didn't fail due to bootstrap errors after adding region to S3 arn and url. 

https://github.com/awslabs/service-workbench-on-aws/pull/394

I am going to go ahead and close this PR once you verify that the new change works for you. Thanks for reporting the issue.

**Comment by kwpark-amzn** [comment]
Great to hear that. Thanks for your effort to fix it. I agree to close this PR even though I do not test.

**Comment by jn1119** [comment]
Fixed in PR https://github.com/awslabs/service-workbench-on-aws/pull/394

**Pull request closed without merging**
