### PR TITLE
feat: Remove API Keys from SWB documentation

### PR DESCRIPTION
**Pull request by stephen-younge**
Description of changes: Remove API Keys from SWB documentation.

Tested by building & deploying documentation Docusaurus site.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Bingjiling** [comment]
Looks good! One thing on deleted file `docs/static/img/deployment/reference/admin_interface_00.jpg`, there's a reference for this picture in [this file](https://github.com/awslabs/service-workbench-on-aws/blob/master/docs/docs/user_guide/introduction.md) line 20.

**Comment by stephen-younge** [comment]
> Looks good! One thing on deleted file `docs/static/img/deployment/reference/admin_interface_00.jpg`, there's a reference for this picture in [this file](https://github.com/awslabs/service-workbench-on-aws/blob/master/docs/docs/user_guide/introduction.md) line 20.

The JPG file above is edited (I cropped out the API Keys icon) but not removed. Do you still see it? (Maybe I messed something up.) I just double-checked by finding the file in [my fork](https://github.com/stephen-younge/service-workbench-on-aws/blob/master/docs/static/img/deployment/reference/admin_interface_00.jpg) which is the basis of this PR.

**Comment by Bingjiling** [comment]
> > Looks good! One thing on deleted file `docs/static/img/deployment/reference/admin_interface_00.jpg`, there's a reference for this picture in [this file](https://github.com/awslabs/service-workbench-on-aws/blob/master/docs/docs/user_guide/introduction.md) line 20.
> 
> The JPG file above is edited (I cropped out the API Keys icon) but not removed. Do you still see it? (Maybe I messed something up.) I just double-checked by finding the file in [my fork](https://github.com/stephen-younge/service-workbench-on-aws/blob/master/docs/static/img/deployment/reference/admin_interface_00.jpg) which is the basis of this PR.

Oops! Sorry I mistaken it for a delete.

**Review by Bingjiling — APPROVED** [review]
Ship it!

**Pull request merged**
