### PR TITLE
feat: Allow uploading a folder to My Studies

### PR DESCRIPTION
**Pull request by nguyen102**
Issue #, if available:

Description of changes:

Allow users to upload a folder to their studies. Video of UI is shown below

https://user-images.githubusercontent.com/3661906/117471421-d5c46200-af25-11eb-8c59-fbc2ad54fa50.mov

Checklist:

- [x] Have you successfully deployed to an AWS account with your changes?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully tested with your changes locally?

AS review ticket id:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by SanketD92 — COMMENTED** [review]
LGTM in general. Could you mention in the PR description how the testing went for this? 
eg. Do the files and folders show up in the correct directory levels in the `studies` folder on workspaces on which they are mounted?

**Comment by nguyen102** [comment]
@SanketD92 
I tested that I was able to upload a folder and the content of the folder showed up in S3. I also tested that the folder's subfolder was uploaded correctly.

I also tested that the content was viewable from em2, windows, sagemaker, ec2-linux, and rstudio.

**Review by jn1119 — COMMENTED** [review]
LGTM, Any scaling bottleneck that we need to take into account? I am guessing there must be some upper bound to how many files/subfolders can be inside a folder. Is there a way to restrict and show a friendly error? Or it is user's responsibility to be reasonable about the folders they choose to upload?

**Comment by nguyen102** [comment]
@jn1119 I did some testing and found that I can upload up to 1,000 files relatively smoothly. However, when trying to upload more than 1000 files the web browser becomes really slow. Therefore, I've set the maximum number of file upload limit at 1000. 

If a user tries to upload a folder that has more than 1000 files, a warning message will be shown. A warning message will also be shown if the number of files is greater than 1000 when multiple folders or files are selected.

**Review by SanketD92 — DISMISSED** [review]
LGTM

**Review by shyogesh-sw — APPROVED** [review]

**Pull request merged**
