### PR TITLE
Fix SageMaker launch permissions

### LINKED ISSUE #1018: [Bug] SageMaker instances can't be launched due to missing tags permission
**Describe the bug**
Service Workbench appears to be unable to launch SageMaker notebook instances at all, due to a missing permission for `sagemaker:AddTags`. This seems to also be the case when custom tags aren't included in the workspace configuration.

**To Reproduce**
1. Install Service Workbench from the latest version.
2. Create a workspace configuration for a SageMaker notebook.
3. Launch a workspace using the new configuration.
4. Wait a few minutes and observe the error.

**Expected behavior**
Expected the notebook to launch :)

**Screenshots**
image
```
Error provisioning environment TestNotebook1. Reason: Errors from CloudFormation: [{LogicalResourceId : SC-455040667691-pp-auh6sv7j6dwr2, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [BasicNotebookInstance]. Rollback requested by user.}, {LogicalResourceId : BasicNotebookInstance, ResourceType : AWS::SageMaker::NotebookInstance, StatusReason : User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/dev-syd-timswb-LaunchConstraint/servicecatalog is not authorized to perform: sagemaker:AddTags on resource: arn:aws:sagemaker:ap-southeast-2:XXXXXXXXXXXX:assumed:notebook-instance/basicnotebookinstance-y4ices04e3sv because no identity-based policy allows the sagemaker:AddTags action (Service: AmazonSageMaker; Status Code: 400; Error Code: AccessDeniedException; Request ID: adee97b7-1c89-47e2-8ca7-5aa374a80004; Proxy: null)}, {LogicalResourceId : IAMRole, ResourceType : AWS::IAM::Role, StatusReason : Resource creation Initiated}, {LogicalResourceId : SecurityGroup, ResourceType : AWS::EC2::SecurityGroup, StatusReason : Resource creation Initiated}, {LogicalResourceId : InstanceRolePermissionBoundary, ResourceType : AWS::IAM::ManagedPolicy, StatusReason : Resource creation Initiated}, {LogicalResourceId : BasicNotebookInstanceLifecycleConfig, ResourceType : AWS::SageMaker::NotebookInstanceLifecycleConfig, StatusReason : Resource creation Initiated}, {LogicalResourceId : SC-455040667691-pp-auh6sv7j6dwr2, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]
```

**Versions (please complete the following information):**
5.2.0
(also replicated on an older 5.0.0 install)

**Additional context**

### PR DESCRIPTION
**Pull request by tdmalone**
Removes a duplicate SageMaker permission, and adds a missing permission for tagging.
Closes #1018.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nguyen102** [comment]
@tdmalone this looks like the right fix. Were you able to deploy and test if this fixes the issue for you?

**Review by nguyen102 — DISMISSED** [review]

**Comment by nguyen102** [comment]
@tdmalone 
Can you add an empty commit to this branch so the `Unit Tests & Code Analysis` status check can be run? You can run this command
`git commit --allow-empty -m 'chore: trigger notification'`

**Comment by tdmalone** [comment]
@nguyen102 

> Were you able to deploy and test if this fixes the issue for you?

Not directly - I've had challenges with the 'official' CI/CD pipeline but we did make the same change on an install where we're running a different pipeline structure and it fixed the issue. Having said that, understand it really should be tested properly so I'm attempting the official pipeline again with this change. Will confirm the result soon.

> Can you add an empty commit to this branch so the Unit Tests & Code Analysis status check can be run?

Done. Apologies for not targeting the correct branch at first!

**Comment by tdmalone** [comment]
Confirming that after the pipeline redeploys this change, the error posted above no longer occurs.

image

**Comment by nguyen102** [comment]
@tdmalone thanks so much for your contribution and testing! I'll get this merged in.

**Review by nguyen102 — APPROVED** [review]

**Pull request merged**
